apiVersion: v1
kind: Service
metadata:
  name: oaicn
  labels:
    app: oaicn
spec:
  ports:
    - name: "enb"
      port: 2152
    - name: "hss-1"
      port: 3868
    - name: "hss-2"
      port: 5868
    - name: "mme"
      port: 2123
    - name: "spgw-1"
      port: 3870
    - name: "spgw-2"
      port: 5870
  selector:
    app: oaicn
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oaicn
  labels:
    app: oaicn
  annotations:
    container.apparmor.security.beta.kubernetes.io/oaicn: unconfined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oaicn
  template:
    metadata:
      labels:
        app: oaicn
    spec:
      containers:
      - name: oaicn
        image: tig4605246/oaicn:1.1
        imagePullPolicy: Always
        command: ["/sbin/init"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys/fs/cgroup/
          name: cgroup
        - mountPath: /lib/modules/
          name: module
        ports:
        - containerPort: 80
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup/
      - name: module
        hostPath:
          path: /lib/modules/