apiVersion: v1
kind: Service
metadata:
  name: oairan
  labels:
    app: oairan
spec:
  ports:
    - name: "enb"
      port: 2152
  selector:
    app: oairan
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oairan
  labels:
    app: oairan
  annotations:
    container.apparmor.security.beta.kubernetes.io/oairan: unconfined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oairan
  template:
    metadata:
      labels:
        app: oairan
    spec:
      containers:
      - name: oairan
        image: mosaic5gecosys/oairan:1.1
        imagePullPolicy: IfNotPresent
        command: ["/sbin/init"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys/fs/cgroup/
          name: cgroup
        - mountPath: /lib/modules/
          name: module
        - mountPath: /dev/bus/usb/
          name: usrp
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: oai
                operator: In
                values:
                - ran
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup/
      - name: module
        hostPath:
          path: /lib/modules/
      - name: usrp
        hostPath:
          path: /dev/bus/usb/