apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: oai
spec:
  ports:
    - port: 3306
  selector:
    app: oai
  clusterIP: None
  # externalIPs:
  #   - "192.168.12.13"
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   labels:
#     app: oai
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: oai
spec:
  selector:
    matchLabels:
      app: oai
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oai
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: linux
        ports:
        - containerPort: 3306
          name: mysql
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: oai
                operator: In
                values:
                - cn
      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claim